name: 'git-restore-mtime'
description: 'Restore the modified timestamp based on git commits'
author: 'Pixelcop Research, Inc.'
branding:
  icon: 'clock'
  color: 'orange'
runs:
  using: 'node12'
  main: 'lib/main.js'
