name: 'Test Suite'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'master'

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.x' ]
    name: 'Ubuntu Latest w/ Python ${{ matrix.python-version }}'

    steps:
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: "2.x"

    # Checkout the requested branch
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: '${{ github.event.inputs.branch }}'

    - name: debug ls
      run: |
        python --version
        git --version
        ls -al

    - name: changes
      run: |
        git whatchanged --pretty=%at

    # Fix timestamps
    - name: restore timestamps
      uses: ./

    # Check timestamps
    - name: validate
      run: |
        ls -al
        e=1568920506
        t=$(stat --format="%Y" jest.config.js)
        if [[ $t -ne $e ]]; then
          echo "timestamp for jest.config.js was '$t'; expected 1568919521"
          exit 1
        fi
